namespace MSS_key_generator.Backend;

public class GenerationData
{
    public ApduCommand ApduCommand { get; }
    public DateTime GenerationDate { get; }

    public GenerationData(ApduCommand command)
    {
        ApduCommand = command;
        GenerationDate = DateTime.Now;
    }

    public override string ToString()
    {
        var s = $"""
Bytes for command: {ApduCommand.ToHex()}
Generated by: {GenerationDate}
""";
        return s;
    }
}